FINNHUB_API_KEY = "d20b0u1r01qmbi8rv080d20b0u1r01qmbi8rv08g"    # optional, enables company news & earnings

# SMTP email
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USERNAME = "info@miamimasterflooring.com"
EMAIL_PASSWORD = ""   # Gmail/Workspace App Password
EMAIL_FROM = "info@miamimasterflooring.com"
EMAIL_TO = "info@miamimasterflooring.com"
ALERT_RECIPIENTS = "info@miamimasterflooring.com"

# Slack Incoming Webhook
SLACK_WEBHOOK_URL = ""

# Telegram Bot
TELEGRAM_BOT_TOKEN = ""
TELEGRAM_CHAT_ID = ""
